# Generated by Django 4.1.1 on 2022-12-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
