# Generated by Django 4.1.1 on 2023-01-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_likes_alter_post_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
    ]
