# Generated by Django 4.1.1 on 2023-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
